server:
  port: 8090

spring:
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/payment/**
